spring:
  application:
    name: ErrorLogProcessor
#  mvc:
#    view:
#      prefix: /view/
#      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/errorlogdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root #test_user
    password: #test_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082
log:
  file:
    path: ./logs/app.log
jwt:
  expirationMs: 1800000
  secret: Ym9wYWlzb2x1dGlvbnNfc2VjcmV0X2tleV9mb3JfZml2ZV8xMl8xMl8yMDI1X3ZlcnlfLXRvbnNfaGVsbG8tX3dvcmxkLXRvbnNfbWFjcm8tdG9uc18tX2hpX3dvcmxk
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example.ErrorLogProcessor: DEBUG
    org.springframework.web.filter: DEBUG
#  servlet:
#    context-path: /test