spring:
  application:
    name: ErrorLogProcessor
#  mvc:
#    view:
#      prefix: /view/
#      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/errorlogdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
log:
  file:
    path: C:/temp/app.log
jwt:
  expirationMs: 3600000
  secret: YourJwtSecretKeyMustBeAtLeast256BitsLongAndShouldBeRandomlyGenerated
#  servlet:
#    context-path: /test